"""In-memory mock data source.

This module is the ONLY place that knows the data is mocked. Each service reads
from here today; tomorrow these constants can be replaced by PostgreSQL queries
or ML-generated output without touching schemas or routes.

Note: risk zones intentionally omit `status` — it is derived from `riskScore`
in the service layer (see app.services.risk.band_for_score).
"""

# --- Region meta -------------------------------------------------------------
REGION_META: dict = {
    "name": "NER",
    "lastUpdated": "2 min ago",
    "center": [25.8, 92.6],
    "zoom": 6,
}

# --- KPI summary (Risk Overview cards) --------------------------------------
KPI_SUMMARY: dict = {
    "criticalZones": {
        "value": 12,
        "note": "Requires immediate attention",
        "band": "CRITICAL",
        "delta": {"dir": "up", "text": "+3 today"},
        "trend": [6, 7, 7, 8, 9, 10, 11, 12],
    },
    "highRiskZones": {
        "value": 28,
        "note": "Elevated across NER",
        "band": "HIGH",
        "delta": {"dir": "up", "text": "+7 since yesterday"},
        "trend": [18, 19, 21, 20, 23, 25, 26, 28],
    },
    "activeAlerts": {
        "value": 9,
        "note": "3 critical",
        "band": "CRITICAL",
        "delta": {"dir": "up", "text": "+2 this hour"},
        "trend": [4, 5, 5, 6, 6, 7, 8, 9],
    },
    "roadsAffected": {
        "value": 17,
        "note": "5 currently blocked",
        "band": "HIGH",
        "delta": {"dir": "flat", "text": "No change"},
        "trend": [15, 16, 16, 17, 17, 16, 17, 17],
    },
}

# --- Risk zones (status derived in the service layer) ------------------------
RISK_ZONES: list[dict] = [
    {
        "id": "zone-aizawl",
        "district": "Aizawl",
        "state": "Mizoram",
        "center": [23.7271, 92.7176],
        "radius": 9000,
        "riskScore": 87,
        "rainfall": 182,
        "soilMoisture": 89,
        "slope": 38,
        "elevation": 1240,
        "predictionWindow": "Next 6–12 hours",
        "populationExposed": 4820,
    },
    {
        "id": "zone-champhai",
        "district": "Champhai",
        "state": "Mizoram",
        "center": [23.4739, 93.3295],
        "radius": 7000,
        "riskScore": 74,
        "rainfall": 141,
        "soilMoisture": 81,
        "slope": 34,
        "elevation": 1310,
        "predictionWindow": "Next 12–24 hours",
        "populationExposed": 2140,
    },
    {
        "id": "zone-kohima",
        "district": "Kohima",
        "state": "Nagaland",
        "center": [25.6751, 94.1086],
        "radius": 8000,
        "riskScore": 68,
        "rainfall": 118,
        "soilMoisture": 76,
        "slope": 31,
        "elevation": 1444,
        "predictionWindow": "Next 24 hours",
        "populationExposed": 3110,
    },
    {
        "id": "zone-shillong",
        "district": "East Khasi Hills",
        "state": "Meghalaya",
        "center": [25.5788, 91.8933],
        "radius": 8500,
        "riskScore": 58,
        "rainfall": 96,
        "soilMoisture": 72,
        "slope": 27,
        "elevation": 1496,
        "predictionWindow": "Next 24–36 hours",
        "populationExposed": 5200,
    },
    {
        "id": "zone-itanagar",
        "district": "Papum Pare",
        "state": "Arunachal Pradesh",
        "center": [27.0844, 93.6053],
        "radius": 9500,
        "riskScore": 63,
        "rainfall": 108,
        "soilMoisture": 74,
        "slope": 33,
        "elevation": 620,
        "predictionWindow": "Next 24 hours",
        "populationExposed": 2760,
    },
    {
        "id": "zone-gangtok",
        "district": "Gangtok",
        "state": "Sikkim",
        "center": [27.3389, 88.6065],
        "radius": 7500,
        "riskScore": 79,
        "rainfall": 156,
        "soilMoisture": 85,
        "slope": 41,
        "elevation": 1650,
        "predictionWindow": "Next 6–12 hours",
        "populationExposed": 3980,
    },
    {
        "id": "zone-imphal",
        "district": "Imphal East",
        "state": "Manipur",
        "center": [24.817, 93.9368],
        "radius": 7000,
        "riskScore": 34,
        "rainfall": 52,
        "soilMoisture": 58,
        "slope": 19,
        "elevation": 786,
        "predictionWindow": "Next 48 hours",
        "populationExposed": 1240,
    },
    {
        "id": "zone-guwahati",
        "district": "Kamrup Metro",
        "state": "Assam",
        "center": [26.1445, 91.7362],
        "radius": 9000,
        "riskScore": 41,
        "rainfall": 68,
        "soilMoisture": 64,
        "slope": 15,
        "elevation": 55,
        "predictionWindow": "Next 36 hours",
        "populationExposed": 6100,
    },
    {
        "id": "zone-agartala",
        "district": "West Tripura",
        "state": "Tripura",
        "center": [23.8315, 91.2868],
        "radius": 7000,
        "riskScore": 18,
        "rainfall": 24,
        "soilMoisture": 44,
        "slope": 9,
        "elevation": 22,
        "predictionWindow": "Stable",
        "populationExposed": 320,
    },
]
